### ISSUE TITLE
Support tuple and dicts for *_on_batch

### ISSUE THREAD

**Issue by Dref360** [ElementAI/baal#17]
**Describe the bug**
If the dataset returns a Dict or Tuple, it breaks.

**To Reproduce**
```python
class MyDS(Dataset):
	def __len__(self):
		return 5

	def __getitem__(self,idx):
		return (torch.randn(3, 20, 20), torch.randn(3, 20, 20)), 5
...

wrapper.train_on_batch(MyDS()[1], ...)

**Expected behavior**

The list of tensors should be acceted and `cuda` should be called on them.

**Vesion (please complete the following information):**
 - BaaL version: 1.0

**Comment by janfreyberg** [comment]
Agreed that this is pretty annoying. Some suggestions:

1) I don't think we need to call `Variable(data)`, since that's a pytorch API that's been deprecated
2) I think we can use the pytorch [default collate function](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py#L42) that's used in DataLoader as inspiration for the types of data we should support. That function works for:
    - any mapping type
    - any sequence type
    - named tuples specifically
    - a few things I don't think we need to support as they should already be turned into tensors by the dataloader, like np arrays, floats, ints, etc

I think we could make a to_cuda function that handles these - I'll make a PR
